title: "Marta Rivera Zurita"
description: "Personal academic website"
theme: minima

author: "Marta Rivera Zurita"
lang: "en"

header_pages:
  - index.md
  - about.md
  - research.md
  - publications.md
  - outreach.md
  - Team.md
